version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    executor: kubernetes/default
    steps:
      - checkout
      - run: mvn clean install
workflows:
  version: 2
  build-deploy:
    jobs:
      - build